development:
 host: localhost
 adapter: postgresql
 encoding: unicode
 database: task_chat
 pool: 5
 username: k41n

test: &test
 host: localhost
 adapter: postgresql
 encoding: unicode
 database: task_chat_test
 pool: 5
 username: k41n
